name: findUnfollowers
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FILE_ID: ${{ secrets.FILE_ID }}

jobs:
  findUnfollowers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          cache: true
      - name: Find users that are not following you back
        run: go run .
